-- 전체 조회
SELECT 	EMP_ID, EMP_NAME 
FROM 	EMPLOYEE;

SELECT	*
FROM	EMPLOYEE;


-- 별칭
SELECT	EMP_NAME AS 이름,
		SALARY*12 AS "1년 급여",
		(SALARY+(SALARY*BONUS_PCT)) * 12 AS 총소득
FROM EMPLOYEE;


SELECT 	EMP_ID AS "empid",
		EMP_NAME AS "이름",
		SALARY AS "급여(원)"
FROM EMPLOYEE;


SELECT 	EMP_NAME,
		SALARY AS 급여(원) 
FROM 	EMPLOYEE;

SELECT 	EMP_NAME,
		SALARY AS 1달급여
FROM 	EMPLOYEE;


-- where절

SELECT 	EMP_NAME AS 이름,
		DEPT_ID AS 부서
FROM 	EMPLOYEE
WHERE 	DEPT_ID = '90';

SELECT 	EMP_NAME AS 이름,
		SALARY AS 급여
FROM 	EMPLOYEE
WHERE 	SALARY > 4000000;

-- 결과값 편집
SELECT 	EMP_ID || EMP_NAME || SALARY
FROM	EMPLOYEE;

SELECT 	EMP_NAME||'의 월급은 '||SALARY||'원 입니다.'
FROM	EMPLOYEE;


-- between
SELECT	EMP_NAME,
		SALARY
FROM	EMPLOYEE
WHERE	SALARY BETWEEN 3500000 AND 5500000;

SELECT 	EMP_NAME,
		SALARY
FROM	EMPLOYEE
WHERE	SALARY >= 3500000
AND		SALARY <= 5500000;

-- like
SELECT 	EMP_NAME, SALARY
FROM	EMPLOYEE
WHERE	EMP_NAME LIKE '김%';

SELECT	EMP_NAME, PHONE
FROM	EMPLOYEE
WHERE	PHONE LIKE '___9_______';


-- _ 구별

SELECT 	EMP_NAME,
		EMAIL
FROM	EMPLOYEE
WHERE	EMAIL LIKE '___#_%' ESCAPE '#';

SELECT 	EMP_NAME,
		EMAIL
FROM	EMPLOYEE
WHERE	EMAIL LIKE '___\_%' ESCAPE '\';


-- NULL

SELECT	EMP_NAME, MGR_ID, DEPT_ID
FROM	EMPLOYEE
WHERE	MGR_ID IS NULL
AND		DEPT_ID IS NULL;

SELECT 	EMP_NAME, DEPT_ID, BONUS_PCT
FROM	EMPLOYEE
WHERE	DEPT_ID IS NULL
AND		BONUS_PCT IS NOT NULL;

-- OR

SELECT 	EMP_NAME, DEPT_ID, SALARY
FROM	EMPLOYEE
WHERE	DEPT_ID IN (60, 90);

SELECT 	EMP_NAME, DEPT_ID, SALARY
FROM	EMPLOYEE
WHERE	DEPT_ID = 60
OR		DEPT_ID = 90;

