-- 1.
SELECT	STUDENT_NAME AS "학생 이름",
		STUDENT_ADDRESS "주소지"
FROM	TB_STUDENT
ORDER BY 1;

-- 2.
SELECT	STUDENT_NAME,
		STUDENT_SSN
FROM	TB_STUDENT
WHERE	ABSENCE_YN = 'Y'
ORDER BY 2 DESC;

-- 3.
SELECT	STUDENT_NAME AS 학생이름,
		STUDENT_NO AS 학번,
		STUDENT_ADDRESS AS "거주지 주소"
FROM	TB_STUDENT
WHERE SUBSTR(STUDENT_ADDRESS, 1, 3) IN ('강원도', '경기도')
AND SUBSTR(STUDENT_NO, 1, 1) = '9'
ORDER BY 1;

-- 4.
SELECT	PROFESSOR_NAME,
		PROFESSOR_SSN
FROM	TB_PROFESSOR
JOIN	TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE	DEPARTMENT_NAME = '법학과'
ORDER BY 2;

-- 5.

SELECT	STUDENT_NO,
		POINT
FROM	TB_GRADE
WHERE	CLASS_NO = 'C3118100'
AND		TERM_NO = '200402'
ORDER BY 2 DESC, 1;

-- 6.
SELECT	STUDENT_NO,
		STUDENT_NAME,
		DEPARTMENT_NAME
FROM	TB_STUDENT
JOIN	TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 2;

-- 7.
SELECT	CLASS_NAME,
		DEPARTMENT_NAME
FROM	TB_CLASS
JOIN	TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 2;

-- 8.
SELECT	CLASS_NAME,
		PROFESSOR_NAME
FROM	TB_CLASS_PROFESSOR
JOIN	TB_PROFESSOR USING (PROFESSOR_NO)
JOIN	TB_CLASS	 USING (CLASS_NO);

-- 9. 
SELECT	CLASS_NAME,
		PROFESSOR_NAME
FROM	TB_CLASS_PROFESSOR
JOIN	TB_PROFESSOR USING (PROFESSOR_NO)
JOIN	TB_CLASS	 USING (CLASS_NO)
JOIN	TB_DEPARTMENT ON (TB_PROFESSOR.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO)
WHERE	CATEGORY = '인문사회'
ORDER BY CLASS_NAME;
					
-- 10.
SELECT 	STUDENT_NO AS 학번,
		STUDENT_NAME AS "학번 이름",
		ROUND(AVG(POINT),1) AS "전체 평점"
FROM	TB_STUDENT
JOIN	TB_GRADE USING (STUDENT_NO)
WHERE DEPARTMENT_NO = (SELECT	DEPARTMENT_NO
						FROM	TB_DEPARTMENT
						WHERE	DEPARTMENT_NAME = '음악학과')
GROUP BY STUDENT_NO, STUDENT_NAME;


-- 11. 이상.. **
SELECT	DEPARTMENT_NAME "학과이름",
		STUDENT_NAME "학생이름",
		PROFESSOR_NAME "지도교수이름"
FROM	TB_STUDENT  
JOIN	TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN	TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE 	STUDENT_NO = 'A313047';

-- 12.
SELECT	STUDENT_NAME, TERM_NO
FROM	TB_GRADE
JOIN	TB_CLASS USING (CLASS_NO)
JOIN	TB_STUDENT USING (STUDENT_NO)
WHERE	CLASS_NAME = '인간관계론'
AND		TERM_NO LIKE '2007%'


-- 13. **



-- 14.
SELECT	STUDENT_NAME AS "학생이름",
		NVL(PROFESSOR_NAME, '지도교수 미지정') AS "지도교수"
FROM	TB_STUDENT
LEFT JOIN TB_PROFESSOR ON (TB_STUDENT.COACH_PROFESSOR_NO = TB_PROFESSOR.PROFESSOR_NO)
WHERE	TB_STUDENT.DEPARTMENT_NO = ( SELECT DEPARTMENT_NO
						  FROM	TB_DEPARTMENT
						  WHERE	DEPARTMENT_NAME = '서반아어학과')
ORDER BY TB_STUDENT.ENTRANCE_DATE;

-- 15.
SELECT	STUDENT_NO AS "학번",
		STUDENT_NAME "이름",
		DEPARTMENT_NAME AS "학과 이름",
		AVG(POINT) AS "평점"
FROM	TB_STUDENT
JOIN 	TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN	TB_GRADE USING(STUDENT_NO)
WHERE	ABSENCE_YN = 'N' 
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0;