-- Basic SELECT

-- 1.
SELECT	DEPARTMENT_NAME AS "학과 명",
		CATEGORY AS 계열
FROM	TB_DEPARTMENT;

-- 2.
SELECT	DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || ' 명 입니다.'
FROM	TB_DEPARTMENT;

-- 3.
SELECT	STUDENT_NAME
FROM	TB_STUDENT
WHERE	ABSENCE_YN = 'Y'
AND		DEPARTMENT_NO = '001'
AND		SUBSTR(STUDENT_SSN, 8, 1) = '2';

-- 4.
SELECT 	STUDENT_NAME
FROM	TB_STUDENT
WHERE	STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119');

-- 5.
SELECT	DEPARTMENT_NAME,
		CATEGORY
FROM	TB_DEPARTMENT
WHERE	CAPACITY BETWEEN 20 AND 30;

-- 6.
SELECT	PROFESSOR_NAME
FROM	TB_PROFESSOR
WHERE	DEPARTMENT_NO IS NULL;

-- 7.
SELECT	STUDENT_NAME
FROM	TB_STUDENT
WHERE	DEPARTMENT_NO IS NULL;

-- 8.
SELECT	CLASS_NO
FROM	TB_CLASS
WHERE	PREATTENDING_CLASS_NO IS NOT NULL;

-- 9.
SELECT 	DISTINCT CATEGORY
FROM 	TB_DEPARTMENT;

-- 10.
SELECT	STUDENT_NO,
		STUDENT_NAME,
		STUDENT_SSN
FROM	TB_STUDENT
WHERE	STUDENT_ADDRESS LIKE '%전주%'
AND		ABSENCE_YN != 'Y'
AND		SUBSTR(ENTRANCE_DATE, 1, 2) = '02';


-- Additional SELECT 

--1.
SELECT	STUDENT_NO 학번,
		STUDENT_NAME 이름,
		ENTRANCE_DATE 입학년도
FROM	TB_STUDENT
WHERE	DEPARTMENT_NO = '002'
ORDER BY 입학년도;

--2.
SELECT	PROFESSOR_NAME,
		PROFESSOR_SSN
FROM	TB_PROFESSOR
WHERE	LENGTH(PROFESSOR_NAME) != 3;

--3.
SELECT	PROFESSOR_NAME 교수이름,
		TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')) - 
		TO_NUMBER('19'||(SUBSTR(PROFESSOR_SSN, 1, 2))) AS 나이
FROM	TB_PROFESSOR
WHERE	SUBSTR(PROFESSOR_SSN, 8, 1) = 1
ORDER BY 나이;

--4.
SELECT	SUBSTR(PROFESSOR_NAME, 2) 이름
FROM	TB_PROFESSOR;

--5. 
SELECT	STUDENT_NO,
		STUDENT_NAME
FROM	TB_STUDENT
WHERE	TO_NUMBER(TO_CHAR(ENTRANCE_DATE,'YYYY')) - 
		TO_NUMBER(TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN, 1, 2), 'RR'), 'RRRR')) = 20;

--6. 
SELECT	TO_CHAR(TO_DATE('2020/12/25', 'YYYY/MM/DD'), 'DAY') AS 요일
FROM 	DUAL;

--7.
SELECT	TO_DATE('99/10/11', 'YY/MM/DD'),
		TO_DATE('49/10/11', 'YY/MM/DD'),
		TO_DATE('99/10/11', 'RR/MM/DD'),
		TO_DATE('49/10/11', 'RR/MM/DD')
FROM 	DUAL;

--8.
SELECT	STUDENT_NO,
		STUDENT_NAME
FROM	TB_STUDENT
WHERE	SUBSTR(STUDENT_NO, 1, 1) != 'A';

--9.
SELECT	ROUND(AVG(POINT), 1) AS 평점
FROM	TB_GRADE
WHERE	STUDENT_NO = 'A517178';

--10.
SELECT	DEPARTMENT_NO AS 학과번호,
		COUNT(STUDENT_NO) AS "학생수(명)"
FROM	TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11.
SELECT 	COUNT(*)
FROM	TB_STUDENT
WHERE	COACH_PROFESSOR_NO IS NULL;

-----------------------------------------

--12.
SELECT	SUBSTR(TERM_NO,1,4) AS 년도,
		ROUND(AVG(POINT), 1)  AS "년도 별 평점"
FROM	TB_GRADE
WHERE	STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4);


--13. ******
-- COUNT 함수는 값이 NULL인 경우 카운트하지 못한다.
-- SUM(CASE WHEN ABSENCE_YN = 'Y' THEN 1 ELSE 0 END) AS "휴학생 수"
SELECT	DEPARTMENT_NO AS 학과코드명,
		SUM(DECODE(ABSENCE_YN, 'Y', 1, 0)) AS "휴학생 수"
FROM	TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--14. 
SELECT	STUDENT_NAME AS 동일이름,
		COUNT(STUDENT_NAME) AS "동명인 수"
FROM	TB_STUDENT
GROUP BY STUDENT_NAME
HAVING	COUNT(STUDENT_NAME) > 1;


--15. ROLL UP 써. GROUP BY(년도, 학기)
SELECT	SUBSTR(TERM_NO, 1, 4) AS 년도,
		SUBSTR(TERM_NO, 5, 2) AS 학기,
		ROUND(AVG(POINT) ,1) AS 평점
FROM	TB_GRADE
WHERE	STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2));