-- DDL �ǽ�����2

-- 1.
CREATE TABLE MEMBER (
	MEMBER_ID	NUMBER(10) PRIMARY KEY,
	NAME		VARCHAR2(25) NOT NULL,
	ADDRESS		VARCHAR2(100),
	CITY		VARCHAR2(30),
	PHONE		VARCHAR2(15),
	JOIN_DATE	DATE DEFAULT SYSDATE NOT NULL
);

-- 2
CREATE TABLE TITLE (
	TITLE_ID	NUMBER(10) PRIMARY KEY,
	TITLE		VARCHAR2(60) NOT NULL,
	DESCRIPTION	VARCHAR2(400) NOT NULL,
	RATING		VARCHAR2(20) CHECK (RATING IN ('18��', '15��', '12��', '��ü��')),
	CATEGORY	VARCHAR2(20) CHECK (CATEGORY IN ('���', '�ڹ̵�', '�׼�', '�Ƶ�', 'SF', '��ť���͸�')),
	RELEASE_DATE	DATE
);

-- 3.
CREATE TABLE TITLE_COPY (
	COPY_ID		NUMBER(10),
	TITLE_ID	NUMBER(10),
	STATUS		VARCHAR2(20) NOT NULL CHECK (STATUS IN ('�뿩����', '�ļ�', '�뿩��', '����')),
	PRIMARY KEY (COPY_ID, TITLE_ID),
	FOREIGN KEY (TITLE_ID) REFERENCES TITLE (TITLE_ID)
);

-- 4.
CREATE TABLE RENTAL (
	BOOK_DATE		DATE DEFAULT SYSDATE,
	MEMBER_ID 		NUMBER(10),
	COPY_ID			NUMBER(10), 
	TITLE_ID		NUMBER(10), 
	ACT_RET_DATE	DATE,
	EXP_RET_DATE	DATE DEFAULT SYSDATE+2,
	PRIMARY KEY		(BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID),
	FOREIGN KEY		(MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
	FOREIGN KEY		(COPY_ID, TITLE_ID) REFERENCES TITLE_COPY (COPY_ID, TITLE_ID)
);

-- 5.
CREATE TABLE RESERVATION (
	RES_DATE		DATE,
	MEMBER_ID		NUMBER(10) REFERENCES MEMBER (MEMBER_ID),
	TITLE_ID		NUMBER(10) REFERENCES TITLE (TITLE_ID),
	PRIMARY KEY		(RES_DATE, MEMBER_ID, TITLE_ID)
)


-----------------------------------------------
-- 2. A
CREATE SEQUENCE MEMBER_ID_SEQ 
INCREMENT BY 1
START WITH 101
NOCACHE;

-- 2. B
CREATE SEQUENCE TITLE_ID_SEQ
INCREMENT BY 1
START WITH 92
NOCACHE;

-- 3.
INSERT INTO TITLE 
VALUES (TO_CHAR(TITLE_ID_SEQ.NEXTVAL), '�ξ����', '�ξ���� ����', '��ü��', '�Ƶ�', '95/10/15');
INSERT INTO TITLE 
VALUES (TO_CHAR(TITLE_ID_SEQ.NEXTVAL), '��Ʈ����', '��Ʈ���� ����', '15��', 'SF', '95/05/19');
INSERT INTO TITLE 
VALUES (TO_CHAR(TITLE_ID_SEQ.NEXTVAL), '���̸���', '���̸��� ����', '18��', 'SF', '95/08/12');
INSERT INTO TITLE 
VALUES (TO_CHAR(TITLE_ID_SEQ.NEXTVAL), '���Ÿ����', '���Ÿ���� ����', '��ü��', '�ڹ̵�', '95/07/12');
INSERT INTO TITLE 
VALUES (TO_CHAR(TITLE_ID_SEQ.NEXTVAL), '���꽺�丮', '���꽺�丮 ����', '��ü��', '���', '95/09/12');
INSERT INTO TITLE 
VALUES (TO_CHAR(TITLE_ID_SEQ.NEXTVAL), '����', '���� ����', '18��', '�׼�', '95/06/01');

SELECT * FROM TITLE;

-- 4.
INSERT INTO MEMBER
VALUES (TO_CHAR(MEMBER_ID_SEQ.NEXTVAL), '��ö��', '������', '����', '899-6666', '90/03/08');
INSERT INTO MEMBER
VALUES (TO_CHAR(MEMBER_ID_SEQ.NEXTVAL), '�̿���', '����', '�λ�', '355-8882', '90/03/08');
INSERT INTO MEMBER
VALUES (TO_CHAR(MEMBER_ID_SEQ.NEXTVAL), '������', '������', '����', '852-5764', '91/06/17');
INSERT INTO MEMBER
VALUES (TO_CHAR(MEMBER_ID_SEQ.NEXTVAL), '����ȣ', 'ȫ����', '����', '559-7777', '90/04/07');
INSERT INTO MEMBER
VALUES (TO_CHAR(MEMBER_ID_SEQ.NEXTVAL), '�κ���', '���ε�', '����', '559-8741', '91/01/18');
INSERT INTO MEMBER
VALUES (TO_CHAR(MEMBER_ID_SEQ.NEXTVAL), '���μ�', '�ϱ�', '����', '542-9988', '91/01/18');

SELECT * FROM MEMBER;

-- 5.
INSERT INTO TITLE_COPY VALUES (1, 92, '�뿩����');
INSERT INTO TITLE_COPY VALUES (1, 93, '�뿩����');
INSERT INTO TITLE_COPY VALUES (2, 93, '�뿩��');
INSERT INTO TITLE_COPY VALUES (1, 94, '�뿩����');
INSERT INTO TITLE_COPY VALUES (1, 95, '�뿩����');
INSERT INTO TITLE_COPY VALUES (2, 95, '�뿩����');
INSERT INTO TITLE_COPY VALUES (3, 95, '�뿩��');
INSERT INTO TITLE_COPY VALUES (1, 96, '�뿩����');
INSERT INTO TITLE_COPY VALUES (1, 97, '�뿩����');

SELECT * FROM TITLE_COPY

-- 6.
SELECT * FROM RENTAL;
DELETE FROM RENTAL WHERE TITLE_ID = 92;
INSERT INTO RENTAL
VALUES (SYSDATE-3, 101, 1, 92, SYSDATE-2, SYSDATE-1);

INSERT INTO RENTAL (BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID, EXP_RET_DATE)
VALUES (SYSDATE-1, 103, 2, 93, SYSDATE+1);

INSERT INTO RENTAL (BOOK_DATE, MEMBER_ID, COPY_ID, TITLE_ID, EXP_RET_DATE)
VALUES (SYSDATE-2, 104, 3, 95, SYSDATE);

INSERT INTO RENTAL
VALUES (SYSDATE-4, 105, 1, 97, SYSDATE-2, SYSDATE-2);

-- 7.
CREATE OR REPLACE VIEW TITLE_AVAIL
AS (SELECT 		TITLE, COPY_ID, STATUS, EXP_RET_DATE
	FROM		TITLE_COPY
	INNER JOIN  TITLE	   USING (TITLE_ID)
	INNER JOIN	RENTAL	   USING (COPY_ID)
	WHERE		TITLE = '�ξ����'
)

SELECT *
FROM RENTAL

-- 8. A
INSERT INTO TITLE
VALUES (TO_CHAR(TITLE_ID_SEQ.NEXTVAL), '��Ÿ����', '��Ÿ���� ����', '��ü��', 'SF', '77/07/07')

INSERT INTO TITLE_COPY
VALUES (1, 98, '�뿩����');

INSERT INTO TITLE_COPY
VALUES (2, 98, '�뿩����');

SELECT *
FROM TITLE_COPY;

-- 8. B
INSERT INTO RESERVATION
VALUES (SYSDATE, 102, 98);

INSERT INTO RESERVATION
VALUES (SYSDATE, 106, 96);

-- 8. C
DELETE FROM RESERVATION WHERE MEMBER_ID = 102;

INSERT INTO RENTAL(MEMBER_ID, COPY_ID, TITLE_ID)
VALUES (102, 1, 98);

UPDATE 	TITLE_COPY
SET		STATUS = '�뿩��'
WHERE	TITLE_ID = 98
AND		COPY_ID	 = 1;

-- 9.
ALTER TABLE TITLE
ADD (PRICE NUMBER(5));

UPDATE	TITLE
SET		PRICE = 3000
WHERE	TITLE_ID = 92;

UPDATE	TITLE
SET		PRICE = 2500
WHERE	TITLE_ID = 93;

UPDATE	TITLE
SET		PRICE = 2000
WHERE	TITLE_ID = 94;

UPDATE	TITLE
SET		PRICE = 3000
WHERE	TITLE_ID = 95;

UPDATE	TITLE
SET		PRICE = 3500
WHERE	TITLE_ID = 96;

UPDATE	TITLE
SET		PRICE = 2000
WHERE	TITLE_ID = 97;

UPDATE	TITLE
SET		PRICE = 1500
WHERE	TITLE_ID = 98;

ALTER TABLE TITLE
MODIFY PRICE NOT NULL;

SELECT *
FROM RENTAL;

-- 10.
SELECT		NAME AS "회원명",
			TITLE AS "제목",
			BOOK_DATE AS "대여일",
			(EXP_RET_DATE - ACT_RET_DATE) AS "기간" 
FROM		RENTAL
INNER JOIN	MEMBER USING (MEMBER_ID)
INNER JOIN	TITLE  USING (TITLE_ID)